### ISSUE TITLE
Look for both discord name and nick name

### ISSUE THREAD

**Issue by faceofcat** [MinecraftModDevelopment/MMDBot#10]
for the
```
!dev curse me
```
command... 

some people have nick names set while their actual name might still match the curse account... so that should be tested as well in case nick can't be found...

also... maybe also try replacing ` ` with `_` and such...
like... for both nick name and actual name... `Face of Cat` should also match `Face_of_Cat`...

**Comment by Poke1650** [comment]
> like... for both nick name and actual name... Face of Cat should also match Face_of_Cat...

Can curse name even have spaces in them? Could just look straight for `_` (and or `-`) if not.
