### ISSUE TITLE
Scripting requests

### ISSUE THREAD

**Issue by Matyrobbrt** [MinecraftModDevelopment/MMDBot#136]
Suggest anything that should be added to scripting here.

**Comment by strikerrocker** [comment]
Gets this implementation of this methods in System class for the bot 
```js
function getMethods(obj,test=[]) {
  var result = [];
  for (var id in obj) {
      if (typeof(obj[id]) == "function" && test.indexOf(id) == -1) {
        result.push(id + "()")
      }
  }
  return result;
}
function getFields(obj,test=[]) {
  var result = [];
  for (var id in obj) {
      if (typeof(obj[id]) != "function" && test.indexOf(id) == -1) {
        result.push(id)
      }
  }
  return result;
}
```
Want this implementation directly as it allows you to remove entries by passing a second parameter of array type with things you don't want implemented.

**Comment by PlatinPython** [comment]
Currently you can only dismiss the resulting message from a script if `/evaluate` was used and the script executed successfully.

This button should also exist on invocation via `!eval` and on failed executions.

**Comment by strikerrocker** [comment]
getCategories method in guild Object for getting all the available categories.
