### ISSUE TITLE
Using Scripting to DM the script creator bypasses limits

### ISSUE THREAD

**Issue by strikerrocker** [MinecraftModDevelopment/MMDBot#137]
**Describe the bug**
When running a script and sending a message in DM the artifical message limit due to time limitation is bypassed. Thousands of messages can be queued to be sent to the user. The bot should have safe guard against this

**To Reproduce**
1 . Send the following msg `!eval
```js
while(true){
   user.openPrivateChannel().sendMessage("Test")
}
````
The above would spam the dm of the person who sents the script

**Expected behavior**
The bot shouldnt be able to send this much messages.

**Comment by TheCurle** [comment]
Can you send an example of the spam here?

**Comment by strikerrocker** [comment]
![image](https://user-images.githubusercontent.com/28724985/154126015-a6406acb-cb2f-4c20-8e15-75bf1960eb5e.png)
From another script. This was about 3.5K messages
