### ISSUE TITLE
Need a command to play a animated fox

### ISSUE THREAD

**Issue by FinnT730** [MinecraftModDevelopment/MMDBot#168]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
I need something like in the video shown here: [here](https://go.matyrobbrt.com/kae7z5vy)

**Describe alternatives you've considered**
Maybe I should not make issues :harold:

**Additional context**
NOPE! I have done the **_April Fools_** !

**Comment by FinnT730** [comment]
:)

**Comment by Matyrobbrt** [comment]
Great idea. The rickroll tho...
