### ISSUE TITLE
New config entries are not added to config file

### ISSUE THREAD

**Issue by williambl** [MinecraftModDevelopment/MMDBot#23]
When a new config entry is added to BotConfig, they are not added to the config file - the config file must be regenerated or the keys added manually.

Requesting to be assigned to this.

**Comment by KiriCattus** [comment]
What are your thoughts on trying out a TOML config rather than the current one we have in place? I've had a look at it's layout in use and it looks nicer than our current one to me at least.

**Comment by KiriCattus** [comment]
Resolved by PR: #40
