### ISSUE TITLE
Add numbering to quote listing

### ISSUE THREAD

**Issue by antoinegag** [MinecraftModDevelopment/MMDBot#78]
**Is your feature request related to a problem? Please describe.**
Trying to find a specific quote number is difficult. The list command (`!quotes`) doesn't have numbering.
![image](https://user-images.githubusercontent.com/25696312/131943013-24f33f51-91f0-4f6a-abdf-02fb5c8c5ae6.png)

**Describe the solution you'd like**
Add numbering to the quotes when listing them

**Describe alternatives you've considered**
You can count them manually or with the page count

**Comment by sciwhiz12** [comment]
Fixed by #79 (commit 9bc424665d1d3001fd3c378aaf1c76f66fa58bea).
